zoom:
  account_id: "test-account"
  client_id: "test-client"
  client_secret: "test-secret"
  base_url: "https://api.zoom.us/v2"

download:
  output_dir: "./downloads"
  concurrent_limit: 3
  retry_attempts: 3
  timeout_seconds: 300

logging:
  level: "info"
  file: "./zoom-downloader.log"
  console: true
  json_format: false

active_users:
  file: "./active_users.txt"
  check_enabled: true