# Example configuration for zoom-to-box
# Copy this file to config.yaml and modify for your environment

# Zoom API Server-to-Server OAuth configuration
zoom:
  account_id: "your_zoom_account_id"
  client_id: "your_zoom_client_id"
  client_secret: "your_zoom_client_secret"
  base_url: "https://api.zoom.us/v2"  # Default Zoom API URL

# Box integration settings (optional)
box:
  enabled: false  # Set to true to enable Box uploads
  client_id: "your_box_client_id"
  client_secret: "your_box_client_secret"
  # Note: files are uploaded to user-specific folders within the service account's root folder

# Download settings
download:
  output_dir: "./downloads"      # Local download directory
  concurrent_limit: 3            # Max concurrent downloads
  retry_attempts: 3              # Max retry attempts for failed downloads
  timeout_seconds: 300           # Download timeout in seconds (5 minutes)

# Logging configuration
logging:
  level: "info"                  # Log level: debug, info, warn, error
  file: "./zoom-downloader.log"  # Log file path
  console: true                  # Enable console output
  json_format: false             # Use JSON log format

# Active users list settings
active_users:
  file: "./active_users.txt"     # Path to active users list file
  check_enabled: true            # Enable user filtering based on active users list

# Environment variable overrides:
# ZOOM_ACCOUNT_ID - overrides zoom.account_id
# ZOOM_CLIENT_ID - overrides zoom.client_id  
# ZOOM_CLIENT_SECRET - overrides zoom.client_secret
# ZOOM_BASE_URL - overrides zoom.base_url
# BOX_CLIENT_ID - overrides box.client_id
# BOX_CLIENT_SECRET - overrides box.client_secret
# DOWNLOAD_OUTPUT_DIR - overrides download.output_dir